# netlify.toml

[build]
  base = "frontend"
  publish = "frontend/dist/clientes-app"
  command = "npm install --legacy-peer-deps && npx ng build --configuration=production"
  node_version = "10"


# Configuração das regras de redirecionamento
[[redirects]]
  # Redireciona todas as solicitações para o index.html
  from = "/*"
  to = "/index.html"
  status = 200
