# netlify.toml

[build]
  base = "frontend"
  publish = "frontend/dist/clientes-app"
  command = "npm install --legacy-peer-deps && ng build --configuration=production"


# Configuração das regras de redirecionamento
[[redirects]]
  # Redireciona todas as solicitações para o index.html
  from = "/*"
  to = "/index.html"
  status = 200
